name: S3 Sync - Production

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  deploy_to_production:
    name: Deploy to S3 Production
    runs-on: ubuntu-latest
    steps:
        - name: Cloudfront Invalidation
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.AWS_DISTRIBUTION_PRODUCTION }}
          PATHS: '/*'
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
